"""
Agent 4 — Watcher.

Post-approval execution with a safety allowlist. Every fix command
generated by the Healer is classified into one of three buckets:

  * safe      — read-only verification (df, kubectl get, curl -I, etc.)
                Executed for real with a timeout; stdout/stderr/exit code
                captured as part of validation.
  * mutation  — destructive (kubectl delete, rm, systemctl restart, ...)
                NEVER executed automatically; logged as "would-run" and
                left to a human operator.
  * unknown   — doesn't match either list. Treated as mutation (fail-safe).

This is the honest middle ground: the Watcher now does real shell work
(so "validation_result" contains actual `df -h` output on a disk-full
alert, not a hard-coded success string), but it never runs anything
that could cause damage without explicit human review.
"""
from __future__ import annotations

import subprocess
from agents.state import NexusState


# ---------------------------------------------------------------------------
# Safety allowlists
# ---------------------------------------------------------------------------

# Read-only command prefixes that are safe to execute automatically.
# Matched case-insensitively against `command.strip()`.
SAFE_COMMAND_PREFIXES: tuple[str, ...] = (
    # Kubernetes — read only
    "kubectl get",
    "kubectl describe",
    "kubectl logs",
    "kubectl top",
    "kubectl version",
    "kubectl rollout history",
    # Disk / memory / processes
    "df ",
    "df\t",
    "du ",
    "du\t",
    "free",
    "uptime",
    "nproc",
    "ps aux",
    "ps -",
    "lsof",
    "vmstat",
    # Network — read only
    "ping -c",
    "dig ",
    "traceroute",
    "mtr --report",
    "ss -",
    "netstat",
    "iftop -t",  # -t = no interactive
    # Service status — read only
    "systemctl status",
    "systemctl is-active",
    "systemctl is-enabled",
    # HTTP / TLS checks
    "curl -s",
    "curl -I",
    "curl -w",
    "curl --head",
    "openssl s_client",
    "openssl x509",
    # DB / queue — read only
    "pg_isready",
    "mysqladmin ping",
    "mysqladmin status",
    "rabbitmqctl list_queues",
    "rabbitmqctl list_consumers",
    "rabbitmqctl status",
    # Docker — read only
    "docker ps",
    "docker stats --no-stream",
    "docker system df",
    "docker images",
    # Kernel / journal — read only (usually needs sudo on real boxes)
    "dmesg",
    "journalctl -u",
    "crontab -l",
    # Utility
    "echo ",
    "date",
    "hostname",
    "whoami",
)

# Destructive prefixes — MUST NEVER be executed automatically.
# If any command matches one of these, it is gated regardless of what
# else appears in it.
MUTATION_COMMAND_PREFIXES: tuple[str, ...] = (
    "rm ",
    "rm\t",
    "rmdir",
    "kubectl delete",
    "kubectl rollout undo",
    "kubectl rollout restart",
    "kubectl apply",
    "kubectl patch",
    "kubectl scale",
    "kubectl exec",
    "systemctl restart",
    "systemctl stop",
    "systemctl start",
    "systemctl reload",
    "service ",
    "kill ",
    "kill\t",
    "killall",
    "pkill",
    "truncate",
    "shutdown",
    "reboot",
    "mkfs",
    "mount ",
    "umount",
    "docker system prune",
    "docker rm ",
    "docker rmi",
    "docker kill",
    "docker restart",
    "docker stop",
    "certbot renew",
    "certbot --",
    "alter system",
    "alter table",
    "drop ",
    "delete from",
    "update ",
    "insert into",
    "create ",
    "grant ",
    "revoke ",
    "iptables",
    "route ",
    "ip route",
    "find ",  # often used with -delete / -exec rm
    "chmod ",
    "chown ",
)

COMMAND_TIMEOUT_SECS = 10  # hung commands should not stall the pipeline
STDOUT_CAP = 600           # characters of stdout to keep per command
STDERR_CAP = 400


# ---------------------------------------------------------------------------
# Classification + execution helpers
# ---------------------------------------------------------------------------

def classify_command(cmd: str) -> str:
    """Return 'safe', 'mutation', or 'unknown'.

    'mutation' wins ties (a command matching both lists is treated as a
    mutation) so we err on the side of not executing. 'unknown' is also
    treated as do-not-execute at the call site.
    """
    stripped = (cmd or "").strip().lower()
    if not stripped:
        return "unknown"
    for prefix in MUTATION_COMMAND_PREFIXES:
        if stripped.startswith(prefix.lower()):
            return "mutation"
    for prefix in SAFE_COMMAND_PREFIXES:
        if stripped.startswith(prefix.lower()):
            return "safe"
    return "unknown"


def run_safe_command(cmd: str) -> dict:
    """Execute a single command with a timeout. Capture stdout/stderr/exit."""
    try:
        completed = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            timeout=COMMAND_TIMEOUT_SECS,
        )
        return {
            "command": cmd,
            "classification": "safe",
            "executed": True,
            "exit_code": completed.returncode,
            "stdout": (completed.stdout or "")[:STDOUT_CAP],
            "stderr": (completed.stderr or "")[:STDERR_CAP],
            "error": None,
        }
    except subprocess.TimeoutExpired:
        return {
            "command": cmd,
            "classification": "safe",
            "executed": False,
            "exit_code": None,
            "stdout": "",
            "stderr": "",
            "error": f"timeout after {COMMAND_TIMEOUT_SECS}s",
        }
    except Exception as exc:  # subprocess-level failures (not shell exit codes)
        return {
            "command": cmd,
            "classification": "safe",
            "executed": False,
            "exit_code": None,
            "stdout": "",
            "stderr": "",
            "error": f"{type(exc).__name__}: {exc}",
        }


def gate_command(cmd: str, classification: str) -> dict:
    """Build a non-executed result for a gated command."""
    reason = (
        "mutation command — requires manual review"
        if classification == "mutation"
        else "unknown command — not on safe allowlist"
    )
    return {
        "command": cmd,
        "classification": classification,
        "executed": False,
        "exit_code": None,
        "stdout": "",
        "stderr": "",
        "error": reason,
    }


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

def watcher_agent(state: NexusState) -> dict:
    """
    Post-approval execution + validation.

    - If not approved: escalate, no execution.
    - If approved: for each fix_command, classify and either run (safe)
      or gate (mutation/unknown). Build `validation_result` from the
      actual captured output.
    """
    if not state.get("human_approved", False):
        return {
            "execution_status": "rejected",
            "validation_result": "Fix was rejected by operator. Escalating.",
            "command_results": [],
            "final_message": (
                "⚠️ Escalated to senior engineer.\n\n"
                f"Alert type: {state.get('alert_type', 'Unknown')}\n"
                f"Root cause: {state.get('root_cause', 'Unknown')}\n"
                f"Diagnosis: {state.get('diagnosis', 'N/A')}"
            ),
        }

    commands = state.get("fix_commands", []) or []
    results: list[dict] = []

    for cmd in commands:
        classification = classify_command(cmd)
        if classification == "safe":
            results.append(run_safe_command(cmd))
        else:
            results.append(gate_command(cmd, classification))

    # -- Tally outcomes -----------------------------------------------------
    executed_ok = sum(1 for r in results if r["executed"] and r["exit_code"] == 0)
    executed_fail = sum(1 for r in results if r["executed"] and r["exit_code"] not in (0, None))
    gated_mutation = sum(1 for r in results if r["classification"] == "mutation")
    gated_unknown = sum(1 for r in results if r["classification"] == "unknown")
    gated_total = gated_mutation + gated_unknown

    # -- Human-readable validation_result -----------------------------------
    lines: list[str] = [
        f"Executed {executed_ok + executed_fail} safe commands "
        f"({executed_ok} ok, {executed_fail} non-zero exit). "
        f"Gated {gated_total} commands ({gated_mutation} mutation, {gated_unknown} unknown) "
        "for manual review.",
    ]
    for r in results:
        if r["executed"]:
            tag = "OK" if r["exit_code"] == 0 else f"FAIL exit={r['exit_code']}"
            preview = (r["stdout"] or r["stderr"] or "").splitlines()[:1]
            preview_str = f" — {preview[0][:120]}" if preview else ""
            lines.append(f"  [EXECUTED {tag}] {r['command']}{preview_str}")
        elif r["classification"] == "safe":
            # Tried to run but failed (timeout / subprocess error)
            lines.append(f"  [EXEC-FAILED] {r['command']} — {r['error']}")
        else:
            lines.append(f"  [GATED {r['classification']}] {r['command']}")
    validation_result = "\n".join(lines)

    # -- Final status -------------------------------------------------------
    # "executed"           = every safe command ran successfully AND no mutation/unknown gated
    # "partially_executed" = safe commands ran (maybe with fails) OR some gating happened
    # Because mutation gating is the norm and expected, we don't treat a
    # gated mutation as a failure — we just report it.
    if executed_fail == 0 and executed_ok + gated_total == len(results):
        status = "executed"
    else:
        status = "partially_executed"

    fix_summary = "\n".join(
        f"  {i+1}. {step}" for i, step in enumerate(state.get("fix_plan", []))
    )

    return {
        "execution_status": status,
        "validation_result": validation_result,
        "command_results": results,
        "final_message": (
            f"✅ Fix processed ({status.replace('_', ' ')}).\n\n"
            f"Plan:\n{fix_summary}\n\n"
            f"Verification: {executed_ok + executed_fail} safe command(s) executed "
            f"({executed_ok} ok), {gated_total} command(s) held for manual review.\n\n"
            f"Estimated recovery time: {state.get('estimated_time', 'N/A')}"
        ),
    }
